language: php
php:
- '7.2'
before_script: composer clearcache; composer install; composer update;  cd test
script: phpunit .
notifications:
  slack:
    secure: jgF3L1XDmXS2xufeaK8EI8NDSDC6wHT2domCbYORvOBH6glEg17NYNJzSqPitjeLkl+4XxPBIHPZK/Ph4k1VensAXJkZ3BYBWy2Xz5iHHQhQBaL14ro35huFW/sik/hHJxAgd5uc1x00aLRJJU9es9iuCmrV/8y15NyUdDO1m9SgtV7qU1yo/bOzjUAgndZnoZTRWnxbCkDJNnpNZlCE7vQ/B1/GkxY1xFDy2LBJugF6ccn6+PpkpS+7YFu2f5QnfHvohlMxEcMMykZwptqoa0wyk4kHXJ9X3cqN9A4rmY3B16OWhJQh5myPOALqKQ3ifLBMhvjUNfog+9KpmHO95BPHDnZdfn8Zrm0nqP0a/JIV895YgByxTG7kiy9okHXBu2tLkA5OvtbT728R8nfbfQtwtDvqgl7OsJX8MmbUFQGdvbjjjP20ZXD3ifnmVuEewzJiJKJzemwcZweDAOJKBaxYCb9BJMY8GWtmOexnwVea2nvho7jYBH5WW1IJydgwBp113n2Rxuf7ZkhgM5bWEQVw7fU1Np/6uzmFKa6axyrfdjVrFs7yyj66Lsxl9VCSx+jteG6V6dVfRwRxYhHDsoXhFpXWH4mG8VYVBIJ+pw1MU7y+d8ZkmK2D2kKf01Ugs2V2qpIHCtPsiD3e969uwl/IFbFWSnqki+UNXfITQ8g=
