<?php

namespace Kiniauth\Services\Security;

class EncryptionService {

    /**
     * Set up the method of encryption.
     *
     * Master Key - (required) It is recommended that the masterKey should be a 32-byte binary string (base64 decoded) and should
     *              be stored on the server, not db.
     *
     * IV - (generated during encryption) Random salt used to ensure uniqueness
     *
     * Tag - (generated during encryption) This is generated by the encryption algorithm as an authentication measure
     *       to ensure the data hasn't been tampered with.
     *
     *
     * @param string $cipher
     */
    public function __construct(private string $cipher = "aes-256-gcm") {

    }

    /**
     * Encrypts the supplied plain text string and returns as a base 64 encoded string
     *
     * @param string $masterKey
     * @param string $plainText
     * @return string
     */
    public function encrypt(string $masterKey, string $plainText): string {
        $iv = openssl_random_pseudo_bytes(openssl_cipher_iv_length($this->cipher));
        $tag = "";

        $encrypted = openssl_encrypt(
            $plainText,
            $this->cipher,
            $masterKey,
            OPENSSL_RAW_DATA,
            $iv,
            $tag
        );

        // Store IV, Tag, and Ciphertext together (base64 for DB storage)
        return base64_encode($iv . $tag . $encrypted);
    }

    /**
     * Returns the unencrypted string for the supplied base 64 encoded data string
     *
     * If the decryption returns false, then either the data has been tampered with or the master key is incorrect.
     *
     * @param string $masterKey
     * @param string $encodedData
     * @return string
     */
    public function decrypt(string $masterKey, string $encodedData): string {
        $data = base64_decode($encodedData);
        $ivLength = openssl_cipher_iv_length($this->cipher);

        $iv = substr($data, 0, $ivLength);
        $tag = substr($data, $ivLength, 16);
        $ciphertext = substr($data, $ivLength + 16);

        return openssl_decrypt(
            $ciphertext,
            $this->cipher,
            $masterKey,
            OPENSSL_RAW_DATA,
            $iv,
            $tag
        );
    }

}